name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker build -f Dockerfile.dev -t kalanadis/react-test .
    - run: docker run -e CI=true kalanadis/react-test npm test
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: ls -al


